---
apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: pulp-galaxy
spec:
  api:
    replicas: 1
  content:
    replicas: 1
  database:
    postgres_storage_class: gp2
  deployment_type: galaxy
  image: quay.io/pulp/galaxy-minimal
  image_pull_policy: IfNotPresent
  image_version: stable
  image_web: quay.io/pulp/galaxy-web
  image_web_version: stable
  ingress_annotations:
    cert-manager.io/issuer: letsencrypt-clusterissuer-staging
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  ingress_class_name: nginx-pulp-powerdns-com
  ingress_host: ansiblegalaxy.romeroalx.work
  ingress_tls_secret: pulp-galaxy-letsencrypt
  ingress_type: ingress
  migration_job:
    container:
      resource_requirements:
        limits:
          cpu: 1
        requests:
          cpu: 1
  object_storage_s3_secret: pulp-galaxy-s3-storage
  pulp_settings:
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    analytics: false
    api_root: /api/galaxy/pulp/
    aws_s3_endpoint_url: http://ppkc-pulp-galaxy-collections.s3.amazonaws.com/
    galaxy_feature_flags:
      ai_deny_index: true
      execution_environments: true
    telemetry: false
  sa_annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::886046197528:role/ppkc-pulp-s3-role
  web:
    replicas: 1
    resource_requirements:
      limits:
        cpu: 800m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  worker:
    replicas: 1
