apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: galaxy-pulp
spec:
  deployment_type: galaxy
  image: quay.io/pulp/galaxy-minimal
  image_version: stable
  image_web: quay.io/pulp/galaxy-web
  image_web_version: stable
  
  api:
    replicas: 1
  content:
    replicas: 1
  worker:
    replicas: 1
  migration_job:
    container:
      resource_requirements:
        requests:
          cpu: 1
        limits:
          cpu: 1
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
    service_annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4

  database:
    postgres_storage_class: gp2
  file_storage_access_mode: "ReadWriteOnce"
  file_storage_size: "10Gi"
  file_storage_storage_class: gp2
  ingress_class_name: alb
  ingress_host: k8s-pulp-galaxypu-7e26074386-d8a4c7a9234303d7.elb.eu-central-1.amazonaws.com
  ingress_type: ingress
  pulp_settings:
    api_root: "/api/galaxy/pulp/"
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    analytics: false
    galaxy_feature_flags:
      execution_environments: True
      ai_deny_index: True
