---
apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: pulp-base
spec:
  api:
    replicas: 1
    resource_requirements:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 150m
        memory: 256Mi
  content:
    replicas: 1
    resource_requirements:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 150m
        memory: 256Mi
  database:
    postgres_storage_class: gp2
  deployment_type: pulp
  image: quay.io/pulp/pulp-minimal
  image_pull_policy: IfNotPresent
  # enable_debugging: true
  image_version: stable
  image_web: quay.io/pulp/pulp-web
  image_web_version: stable
  # ingress_annotations:
  #   cert-manager.io/issuer: letsencrypt-issuer
  #   nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  ingress_class_name: alb
  ingress_host: pulp-test.romeroalx.work
  # ingress_tls_secret: pulp-test-letsencrypt
  ingress_type: ingress
  migration_job:
    container:
      resource_requirements:
        limits:
          cpu: 1
        requests:
          cpu: 1
  pulp_settings:
    allowed_export_paths:
      - /tmp
    allowed_import_paths:
      - /tmp
    api_root: /pulp/
    telemetry: false
  # signing_scripts: signing-scripts
  # signing_secret: signing-secret
  web:
    replicas: 1
    resource_requirements:
      limits:
        cpu: 800m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  worker:
    replicas: 1
    resource_requirements:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 150m
        memory: 256Mi