---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pdns-vault-static-secret
  namespace: external-dns
spec:
  type: kv-v1
  mount: pdns
  path: apikey
  refreshAfter: 60s
  vaultAuthRef: static-auth
  destination:
    name: pdns-api-secret
    create: true
