---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: external-dns
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pdns-api-key
    serviceAccount: external-dns

